metadata:
  environment: development
  version: "1.0"

http:
  allowed_origins:
    - https://*
    - http://*
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed_headers:
    - Accept
    - Authorization
    - Content-Type
    - X-CSRF-Token
  exposed_headers:
    - Link
  allow_credentials: false
  max_age: 300

redis:
  connection_uri: localhost:6379
  password: ""

oauth_settings:
  provider: "github"
  client_id: ""
  client_secret: ""
  access_token_url: ""
  authorize_url: ""
  redirect_uri: ""
  api_base_url: ""
  scope: []
  state: ""

core_settings:
  github_archive_repo: axon-archive

mongodb_settings:
  development:
    connection_uri: "mongodb://127.0.0.1:27017"

  production:
    connection_uri: ""

axon_client:
  auth_redirect_url: "http://localhost:4514/folders"
  error_url: "http://localhost:4514/error"
