// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "stephen.sanwo@icloud.com",
        "contact": {
            "name": "Stephen Sanwo",
            "email": "stephen.sanwo@icloud.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth-github": {
            "get": {
                "description": "Oauth with Github",
                "tags": [
                    "User"
                ],
                "summary": "Oauth with Github",
                "operationId": "github-oauth",
                "responses": {
                    "200": {
                        "description": "Ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth-user": {
            "get": {
                "description": "Query Authenticated User",
                "tags": [
                    "User"
                ],
                "summary": "Query Authenticated User",
                "operationId": "get-auth-user",
                "responses": {
                    "200": {
                        "description": "User",
                        "schema": {
                            "$ref": "#/definitions/types.Folder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/callback": {
            "get": {
                "description": "AuthCallback",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "AuthCallback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/axon-auth_src_types.BaseResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping the server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ping"
                ],
                "summary": "Ping the server",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/axon-auth_src_types.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "axon-auth_src_types.BaseResponse": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "types.Folder": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "folder_name": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8301",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Axon Auth API",
	Description:      "Axon Auth API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
