import { editor } from "monaco-editor";

export const BASE_EDITOR_OPTIONS: editor.IStandaloneEditorConstructionOptions =
  {
    minimap: {
      enabled: false,
    },
    fontFamily: "IBM Plex Mono",
    fontSize: 14,
    tabSize: 8,
    padding: {
      top: 14,
    },
    detectIndentation: true,
    readOnly: false,
    autoIndent: "advanced",
    bracketPairColorization: {
      enabled: true,
    },
    lineNumbers: "on",
    scrollBeyondLastLine: true,
    wordWrap: "on",
    wrappingIndent: "indent",
    wrappingStrategy: "advanced",
    renderLineHighlight: "all",
    overviewRulerBorder: false,
    hideCursorInOverviewRuler: false,
    renderLineHighlightOnlyWhenFocus: false,
    renderValidationDecorations: "off", // Turn off validation errors
    renderWhitespace: "all",
    selectionHighlight: false,
    "semanticHighlighting.enabled": false,
    formatOnType: true,
    formatOnPaste: true,
    suggestOnTriggerCharacters: true,
    suggestSelection: "recentlyUsed",
    acceptSuggestionOnEnter: "smart",
    quickSuggestions: true,
    quickSuggestionsDelay: 100,
    suggestFontSize: 14,
    suggestLineHeight: 20,
    suggest: {
      preview: false,
      showFiles: false,
      showMethods: false,
      showFunctions: false,
      showConstructors: false,
      showVariables: false,
      showProperties: false,
      showEvents: false,
      showOperators: false,
      showKeywords: false,
      showWords: false,
      showColors: false,
      showModules: false,
      showClasses: false,
      showInterfaces: false,
      showStructs: false,
      showEnums: false,
      showEnumMembers: false,
      showConstants: false,
      showReferences: false,
      showFolders: false,
      showTypeParameters: false,
      showIssues: false,
      showUsers: false,
      showSnippets: false,
      showDeprecated: false,
      filterGraceful: false,
      snippetsPreventQuickSuggestions: true,
    },
    folding: true,
    scrollbar: {
      vertical: "visible",
      horizontal: "hidden",
    },
  };
