import { editor } from "monaco-editor";
import { Theme } from "src/types/theme";

export function getCustomEditorTheme(theme: Theme) {
  return {
    base: "vs-dark",
    inherit: true,
    colors: {
      "editor.background": theme?.colors.bg.default,
      "editorStickScrollbar.background": theme?.colors.bg.default,
      "breadcrumb.background": theme?.colors.bg.default,
      "editorGutter.background": theme?.colors.bg.default,
      "editorMarkerNavigation.background": theme?.colors.bg.default,

      // Input
      "input.background": theme?.colors.bg.default,
      "input.foreground": theme?.colors.text.grayLight,
      "inputOption.activeBorder": theme?.colors.primary.default,
      "inputOption.hoverBackground": theme?.colors.primary.variant1,

      // List
      "list.activeSelectionBackground": theme?.colors.primary.variant1,

      "dropdown.background": theme?.colors.bg.default,
      "dropdown.border": theme?.colors.bg.default,
      "checkbox.background": theme?.colors.bg.default,
      "checkbox.border": theme?.colors.bg.default,
      "menu.background": theme?.colors.bg.default,

      "menu.selectionBackground": theme?.colors.primary.variant1,

      // Scrollbar
      "scrollbar.shadow": theme?.colors.bg.default,
      "scrollbarSlider.activeBackground": theme?.colors.bg.variant2,
      "scrollbarSlider.background": theme?.colors.bg.default,
      "scrollbarSlider.hoverBackground": theme?.colors.bg.variant2,

      // "editor.background": theme?.colors.bg.default,
      // "editorStickScrollbar.background": theme?.colors.bg.default,
      // "breadcrumb.background": theme?.colors.bg.default,
      // "editorGutter.background": theme?.colors.bg.default,
      // "editorMarkerNavigation.background": theme?.colors.bg.default,
      // // Input
      // "input.background": theme?.colors.bg.default,
      // "input.foreground": theme?.colors.text.grayLight,
      // "inputOption.activeBorder": theme?.colors.primary.default,
      // "inputOption.hoverBackground": theme?.colors.primary.variant1,
      // // List
      // "list.activeSelectionBackground": theme?.colors.primary.variant1,
      // "dropdown.background": theme?.colors.bg.default,
      // "dropdown.border": theme?.colors.bg.default,
      // "checkbox.background": theme?.colors.bg.default,
      // "checkbox.border": theme?.colors.bg.default,
      // "menu.background": theme?.colors.bg.default,
      // "menu.selectionBackground": theme?.colors.primary.variant1,
      // // Scrollbar
      // "scrollbar.shadow": theme?.colors.bg.default,
      // "scrollbarSlider.activeBackground": theme?.colors.bg.variant2,
      // "scrollbarSlider.background": theme?.colors.bg.default,
      // "scrollbarSlider.hoverBackground": theme?.colors.bg.variant2,
      // "activityBar.background": "#282c34",
      // "activityBar.foreground": "#d7dae0",
      // "activityBarBadge.background": "#4d78cc",
      // "activityBarBadge.foreground": "#f8fafd",
      // "badge.background": "#282c34",
      // "button.background": "#404754",
      // "button.secondaryBackground": "#30333d",
      // "button.secondaryForeground": "#c0bdbd",
      // "checkbox.border": "#404754",
      // "debugToolBar.background": "#21252b",
      // descriptionForeground: "#abb2bf",
      // "diffEditor.insertedTextBackground": "#00809b33",
      // "dropdown.background": "#21252b",
      // "dropdown.border": "#21252b",
      // "editor.background": "#282c34",
      // "editor.findMatchBackground": "#d19a6644",
      // "editor.findMatchBorder": "#ffffff5a",
      // "editor.findMatchHighlightBackground": "#ffffff22",
      // "editor.foreground": "#abb2bf",
      // "editorBracketHighlight.foreground1": "#d19a66",
      // "editorBracketHighlight.foreground2": "#c678dd",
      // "editorBracketHighlight.foreground3": "#56b6c2",
      // "editorHoverWidget.highlightForeground": "#61afef",
      // "editorInlayHint.foreground": "#abb2bf",
      // "editorInlayHint.background": "#2c313c",
      // "editor.lineHighlightBackground": "#2c313c",
      // "editorLineNumber.activeForeground": "#abb2bf",
      // "editorGutter.addedBackground": "#109868",
      // "editorGutter.deletedBackground": "#9A353D",
      // "editorGutter.modifiedBackground": "#948B60",
      // "editorOverviewRuler.addedBackground": "#109868",
      // "editorOverviewRuler.deletedBackground": "#9A353D",
      // "editorOverviewRuler.modifiedBackground": "#948B60",
      // "editor.selectionBackground": "#67769660",
      // "editor.selectionHighlightBackground": "#ffffff10",
      // "editor.selectionHighlightBorder": "#dddddd",
      // "editor.wordHighlightBackground": "#d2e0ff2f",
      // "editor.wordHighlightBorder": "#7f848e",
      // "editor.wordHighlightStrongBackground": "#abb2bf26",
      // "editor.wordHighlightStrongBorder": "#7f848e",
      // "editorBracketMatch.background": "#515a6b",
      // "editorBracketMatch.border": "#515a6b",
      // "editorCursor.background": "#ffffffc9",
      // "editorCursor.foreground": "#528bff",
      // "editorError.foreground": "#c24038",
      // "editorGroup.background": "#181a1f",
      // "editorGroup.border": "#181a1f",
      // "editorGroupHeader.tabsBackground": "#21252b",
      // "editorHoverWidget.background": "#21252b",
      // "editorHoverWidget.border": "#181a1f",
      // "editorIndentGuide.activeBackground": "#c8c8c859",
      // "editorIndentGuide.background": "#3b4048",
      // "editorLineNumber.foreground": "#495162",
      // "editorMarkerNavigation.background": "#21252b",
      // "editorRuler.foreground": "#abb2bf26",
      // "editorSuggestWidget.background": "#21252b",
      // "editorSuggestWidget.border": "#181a1f",
      // "editorSuggestWidget.selectedBackground": "#2c313a",
      // "editorWarning.foreground": "#d19a66",
      // "editorWhitespace.foreground": "#ffffff1d",
      // "editorWidget.background": "#21252b",
      // focusBorder: "#3e4452",
      // "gitDecoration.ignoredResourceForeground": "#636b78",
      // "input.background": "#1d1f23",
      // "input.foreground": "#abb2bf",
      // "list.activeSelectionBackground": "#2c313a",
      // "list.activeSelectionForeground": "#d7dae0",
      // "list.focusBackground": "#323842",
      // "list.focusForeground": "#f0f0f0",
      // "list.highlightForeground": "#ecebeb",
      // "list.hoverBackground": "#2c313a",
      // "list.hoverForeground": "#abb2bf",
      // "list.inactiveSelectionBackground": "#323842",
      // "list.inactiveSelectionForeground": "#d7dae0",
      // "list.warningForeground": "#d19a66",
      // "menu.foreground": "#abb2bf",
      // "menu.separatorBackground": "#343a45",
      // "minimapGutter.addedBackground": "#109868",
      // "minimapGutter.deletedBackground": "#9A353D",
      // "minimapGutter.modifiedBackground": "#948B60",
      // "panel.border": "#3e4452",
      // "panelSectionHeader.background": "#21252b",
      // "peekViewEditor.background": "#1b1d23",
      // "peekViewEditor.matchHighlightBackground": "#29244b",
      // "peekViewResult.background": "#22262b",
      // "scrollbar.shadow": "#23252c",
      // "scrollbarSlider.activeBackground": "#747d9180",
      // "scrollbarSlider.background": "#4e566660",
      // "scrollbarSlider.hoverBackground": "#5a637580",
      // "settings.focusedRowBackground": "#282c34",
      // "settings.headerForeground": "#fff",
      // "sideBar.background": "#21252b",
      // "sideBar.foreground": "#abb2bf",
      // "sideBarSectionHeader.background": "#282c34",
      // "sideBarSectionHeader.foreground": "#abb2bf",
      // "statusBar.background": "#21252b",
      // "statusBar.debuggingBackground": "#cc6633",
      // "statusBar.debuggingBorder": "#ff000000",
      // "statusBar.debuggingForeground": "#ffffff",
      // "statusBar.foreground": "#9da5b4",
      // "statusBar.noFolderBackground": "#21252b",
      // "statusBarItem.remoteBackground": "#4d78cc",
      // "statusBarItem.remoteForeground": "#f8fafd",
      // "tab.activeBackground": "#282c34",
      // "tab.activeBorder": "#b4b4b4",
      // "tab.activeForeground": "#dcdcdc",
      // "tab.border": "#181a1f",
      // "tab.hoverBackground": "#323842",
      // "tab.inactiveBackground": "#21252b",
      // "tab.unfocusedHoverBackground": "#323842",
      // "terminal.ansiBlack": "#3f4451",
      // "terminal.ansiBlue": "#4aa5f0",
      // "terminal.ansiBrightBlack": "#4f5666",
      // "terminal.ansiBrightBlue": "#4dc4ff",
      // "terminal.ansiBrightCyan": "#4cd1e0",
      // "terminal.ansiBrightGreen": "#a5e075",
      // "terminal.ansiBrightMagenta": "#de73ff",
      // "terminal.ansiBrightRed": "#ff616e",
      // "terminal.ansiBrightWhite": "#e6e6e6",
      // "terminal.ansiBrightYellow": "#f0a45d",
      // "terminal.ansiCyan": "#42b3c2",
      // "terminal.ansiGreen": "#8cc265",
      // "terminal.ansiMagenta": "#c162de",
      // "terminal.ansiRed": "#e05561",
      // "terminal.ansiWhite": "#d7dae0",
      // "terminal.ansiYellow": "#d18f52",
      // "terminal.background": "#282c34",
      // "terminal.border": "#3e4452",
      // "terminal.foreground": "#abb2bf",
      // "terminal.selectionBackground": "#abb2bf30",
      // "textBlockQuote.background": "#2e3440",
      // "textBlockQuote.border": "#4b5362",
      // "textLink.foreground": "#61afef",
      // "textPreformat.foreground": "#d19a66",
      // "titleBar.activeBackground": "#282c34",
      // "titleBar.activeForeground": "#9da5b4",
      // "titleBar.inactiveBackground": "#282c34",
      // "titleBar.inactiveForeground": "#6b717d",
      // "tree.indentGuidesStroke": "#ffffff1d",
      // "walkThrough.embeddedEditorBackground": "#2e3440",
      // "welcomePage.buttonHoverBackground": "#404754",

      // Jetbrains
      "terminal.background": "#151515",
      //inlayHints
      "editorInlayHint.foreground": "#838383",
      "editorInlayHint.background": "#2b2b2b",
      // "editorInlayHint.typeForeground":
      // "editorInlayHint.typeBackground":
      // "editorInlayHint.parameterForeground":
      // "editorInlayHint.parameterBackground":
      foreground: "#d6d6dd",
      focusBorder: "#d6d6dd00",
      // debug terminal
      "selection.background": "#163761",
      // "scrollbar.shadow": "#d6d6dd00",
      "activityBar.foreground": "#e3e1e3",
      "activityBar.background": "#181818",
      "activityBar.inactiveForeground": "#7a797a",
      "activityBarBadge.foreground": "#d6d6dd",
      "activityBarBadge.background": "#228df2",
      "activityBar.border": "#383838",
      "activityBar.activeBackground": "#181818",
      "sideBar.background": "#181818",
      "sideBar.foreground": "#d1d1d1",
      "sideBarSectionHeader.background": "#18181800",
      "sideBarSectionHeader.foreground": "#d1d1d1",
      "sideBarSectionHeader.border": "#d1d1d100",
      "sideBarTitle.foreground": "#d1d1d1",
      // sidebar border
      "sideBar.border": "#383838",
      "list.inactiveSelectionBackground": "#3c3b3c",
      "list.inactiveSelectionForeground": "#d6d6dd",
      "list.hoverBackground": "#2a282a",
      "list.hoverForeground": "#d6d6dd",
      // "list.activeSelectionBackground": "#163761",
      "list.activeSelectionForeground": "#d6d6dd",
      "tree.indentGuidesStroke": "#d6d6dd00",
      "list.dropBackground": "#d6d6dd00",
      "list.highlightForeground": "#d6d6dd",
      "list.focusBackground": "#2d2d2d",
      "list.focusForeground": "#d6d6dd",
      "listFilterWidget.background": "#5b51ec",
      "listFilterWidget.outline": "#00000000",
      "listFilterWidget.noMatchesOutline": "#f14c4c",
      "statusBar.foreground": "#d6d6dd",
      "statusBar.background": "#181818",
      "statusBarItem.hoverBackground": "#d6d6dd20",
      "statusBar.border": "#383838",
      "statusBar.debuggingBackground": "#ea7620",
      "statusBar.debuggingForeground": "#e7e7e7",
      "statusBar.debuggingBorder": "#d6d6dd00",
      "statusBar.noFolderBackground": "#181818",
      "statusBar.noFolderForeground": "#6b6b6b",
      "statusBar.noFolderBorder": "#d6d6dd00",
      "statusBarItem.remoteBackground": "#5b51ec",
      "statusBarItem.remoteForeground": "#d6d6dd",
      "menubar.selectionForeground": "#d6d6dd",
      "menubar.selectionBackground": "#d6d6dd20",
      "menubar.selectionBorder": "#d6d6dd00",
      "menu.foreground": "#d6d6dd",
      // "menu.background": "#292929",
      "menu.selectionForeground": "#d6d6dd",
      // "menu.selectionBackground": "#194176",
      "menu.selectionBorder": "#00000000",
      "menu.separatorBackground": "#3e3e3e",
      "menu.border": "#000000",
      "button.background": "#228df2",
      "button.foreground": "#d6d6dd",
      "button.hoverBackground": "#359dff",
      "button.secondaryForeground": "#d6d6dd",
      "button.secondaryBackground": "#1d1d1d",
      "button.secondaryHoverBackground": "#303030",
      // "input.background": "#1d1d1d00",
      "input.border": "#20204208",
      // "input.foreground": "#d6d6dd",
      "inputOption.activeBackground": "#de3c72",
      // "inputOption.activeBorder": "#d6d6dd00",
      "inputOption.activeForeground": "#d6d6dd",
      "input.placeholderForeground": "#7b7b7b",
      "textLink.foreground": "#228df2",
      // "editor.background": "#181818",
      "editor.foreground": "#d6d6dd",
      "editorLineNumber.foreground": "#535353",
      "editorCursor.foreground": "#d6d6dd",
      "editorCursor.background": "#181818",
      "editor.selectionBackground": "#163761",
      "editor.inactiveSelectionBackground": "#363636",
      "editorWhitespace.foreground": "#737373",
      "editor.selectionHighlightBackground": "#16376170",
      "editor.selectionHighlightBorder": "#d6d6dd00",
      "editor.findMatchBackground": "#163764",
      "editor.findMatchBorder": "#00000000",
      "editor.findMatchHighlightBackground": "#7c511a",
      "editor.findMatchHighlightBorder": "#d7d7dd02",
      "editor.findRangeHighlightBackground": "#1d1d1d",
      "editor.findRangeHighlightBorder": "#d6d6dd00",
      "editor.rangeHighlightBackground": "#1d1d1d",
      "editor.rangeHighlightBorder": "#38383800",
      "editor.hoverHighlightBackground": "#5b51ec70",
      "editor.wordHighlightStrongBackground": "#16376170",
      "editor.wordHighlightStrongBorder": "#d6d6dd00",
      "editor.wordHighlightBackground": "#ff000000",
      "editor.wordHighlightBorder": "#d6d6dd00",
      "editor.lineHighlightBackground": "#292929",
      "editor.lineHighlightBorder": "#d6d6dd00",
      "editorLineNumber.activeForeground": "#c2c2c2",
      "editorLink.activeForeground": "#228df2",
      "editorIndentGuide.background": "#383838",
      // 缩进参考线
      "editorIndentGuide.activeBackground": "#737377",
      "editorRuler.foreground": "#383838",
      "editorBracketMatch.background": "#163761",
      "editorBracketMatch.border": "#d6d6dd00",
      "editor.foldBackground": "#1d1d1d",
      "editorOverviewRuler.background": "#25252500",
      "editorOverviewRuler.border": "#7f7f7f4d",
      "editorError.foreground": "#f14c4c",
      "editorError.background": "#B73A3400",
      "editorError.border": "#d6d6dd00",
      "editorWarning.foreground": "#ea7620",
      "editorWarning.background": "#A9904000",
      "editorWarning.border": "#d6d6dd00",
      "editorInfo.foreground": "#228df2",
      "editorInfo.background": "#d6d6dd00",
      "editorInfo.border": "#d6d6dd00",
      // "editorGutter.background": "#181818",
      "editorGutter.modifiedBackground": "#e5b95c",
      "editorGutter.addedBackground": "#15ac91",
      "editorGutter.deletedBackground": "#f14c4c",
      "editorGutter.foldingControlForeground": "#d6d6dd",
      "editorCodeLens.foreground": "#d6d6dd",
      "editorGroup.border": "#383838",
      "diffEditor.insertedTextBackground": "#83d6c530",
      "diffEditor.insertedTextBorder": "#d6d6dd00",
      "diffEditor.removedTextBackground": "#f14c4c30",
      "diffEditor.removedTextBorder": "#d6d6dd00",
      "diffEditor.border": "#383838",
      "panel.background": "#292929",
      "panel.border": "#181818",
      "panelTitle.activeBorder": "#d6d6dd",
      "panelTitle.activeForeground": "#d6d6dd",
      "panelTitle.inactiveForeground": "#d6d6dd",
      "badge.background": "#228df2",
      "badge.foreground": "#d6d6dd",
      "terminal.foreground": "#d6d6dd",
      "terminal.selectionBackground": "#636262fd",
      "terminalCursor.background": "#5b51ec",
      "terminalCursor.foreground": "#d6d6dd",
      "terminal.border": "#383838",
      "terminal.ansiBlack": "#676767",
      "terminal.ansiBlue": "#4c9df3",
      "terminal.ansiBrightBlack": "#676767",
      "terminal.ansiBrightBlue": "#4c9df3",
      "terminal.ansiBrightCyan": "#75d3ba",
      "terminal.ansiBrightGreen": "#15ac91",
      "terminal.ansiBrightMagenta": "#e567dc",
      "terminal.ansiBrightRed": "#f14c4c",
      "terminal.ansiBrightWhite": "#d6d6dd",
      "terminal.ansiBrightYellow": "#e5b95c",
      "terminal.ansiCyan": "#75d3ba",
      "terminal.ansiGreen": "#15ac91",
      "terminal.ansiMagenta": "#e567dc",
      "terminal.ansiRed": "#f14c4c",
      "terminal.ansiWhite": "#d6d6dd",
      "terminal.ansiYellow": "#e5b95c",
      // "breadcrumb.background": "#181818",
      "breadcrumb.foreground": "#676767",
      "breadcrumb.focusForeground": "#d6d6dd",
      "editorGroupHeader.border": "#d6d6dd00",
      "editorGroupHeader.tabsBackground": "#292929",
      "editorGroupHeader.tabsBorder": "#d6d6dd00",
      "tab.activeForeground": "#d6d6dd",
      "tab.border": "#d6d6dd00",
      "tab.activeBackground": "#181818",
      "tab.activeBorder": "#d6d6dd00",
      "tab.activeBorderTop": "#d6d6dd",
      "tab.inactiveBackground": "#292929",
      "tab.inactiveForeground": "#d6d6dd",
      "tab.hoverForeground": "#d6d6dd",
      "tab.hoverBorder": "#6d6d7071",
      // "scrollbarSlider.background": "#67676750",
      // "scrollbarSlider.hoverBackground": "#676767",
      // "scrollbarSlider.activeBackground": "#676767",
      "progressBar.background": "#15ac91",
      "widget.shadow": "#111111eb",
      "editorWidget.foreground": "#d6d6dd",
      "editorWidget.background": "#292929",
      "editorWidget.resizeBorder": "#ea7620",
      "pickerGroup.border": "#383838",
      "pickerGroup.foreground": "#d6d6dd",
      "debugToolBar.background": "#343334",
      "debugToolBar.border": "#383838",
      "notifications.foreground": "#d6d6dd",
      "notifications.background": "#1d1d1d",
      "notificationToast.border": "#383838",
      "notificationsErrorIcon.foreground": "#f14c4c",
      "notificationsWarningIcon.foreground": "#ea7620",
      "notificationsInfoIcon.foreground": "#228df2",
      "notificationCenter.border": "#2c2c2c",
      "notificationCenterHeader.foreground": "#d6d6dd",
      "notificationCenterHeader.background": "#2c2c2c",
      "notifications.border": "#2c2c2c",
      "gitDecoration.addedResourceForeground": "#5a964d",
      "gitDecoration.conflictingResourceForeground": "#aaa0fa",
      "gitDecoration.deletedResourceForeground": "#f14c4c",
      "gitDecoration.ignoredResourceForeground": "#666666",
      "gitDecoration.modifiedResourceForeground": "#1a85f6",
      "gitDecoration.stageDeletedResourceForeground": "#f14c4c",
      "gitDecoration.stageModifiedResourceForeground": "#1a85f6",
      "gitDecoration.submoduleResourceForeground": "#1a85f6",
      "gitDecoration.untrackedResourceForeground": "#3ea17f",
      // "editorMarkerNavigation.background": "#2d2d30",
      "editorMarkerNavigationError.background": "#f14c4c",
      "editorMarkerNavigationWarning.background": "#e5b95c",
      "editorMarkerNavigationInfo.background": "#4c9df3",
      "merge.currentHeaderBackground": "#83d6c595",
      "merge.currentContentBackground": "#1a493d",
      "merge.incomingHeaderBackground": "#395F8F",
      "merge.incomingContentBackground": "#28384B",
      "merge.commonHeaderBackground": "#323232",
      "merge.commonContentBackground": "#1d1d1d",
      "editorSuggestWidget.background": "#1d1d1d",
      "editorSuggestWidget.border": "#383838",
      "editorSuggestWidget.foreground": "#d6d6dd",
      "editorSuggestWidget.highlightForeground": "#d6d6dd",
      "editorSuggestWidget.selectedBackground": "#163761",
      "editorHoverWidget.foreground": "#d6d6dd",
      "editorHoverWidget.background": "#1d1d1d",
      "editorHoverWidget.border": "#383838",
      "peekView.border": "#383838",
      "peekViewEditor.background": "#001f33",
      "peekViewEditorGutter.background": "#001f33",
      "peekViewEditor.matchHighlightBackground": "#ea762070",
      "peekViewEditor.matchHighlightBorder": "#d6d6dd00",
      "peekViewResult.background": "#1d1d1d",
      "peekViewResult.fileForeground": "#d6d6dd",
      "peekViewResult.lineForeground": "#d6d6dd",
      "peekViewResult.matchHighlightBackground": "#ea762070",
      "peekViewResult.selectionBackground": "#363636",
      "peekViewResult.selectionForeground": "#d6d6dd",
      "peekViewTitle.background": "#1d1d1d",
      "peekViewTitleDescription.foreground": "#d6d6dd",
      "peekViewTitleLabel.foreground": "#d6d6dd",
      "icon.foreground": "#d6d6dd",
      // "checkbox.background": "#1d1d1d",
      "checkbox.foreground": "#d6d6dd",
      // "checkbox.border": "#4f4f4f",
      // "checkbox.border": "#d6d6dd00",
      // "dropdown.background": "#1d1d1d",
      "dropdown.foreground": "#d6d6dd",
      // "dropdown.border": "#383838",
      "minimapGutter.addedBackground": "#15ac91",
      "minimapGutter.modifiedBackground": "#e5b95c",
      "minimapGutter.deletedBackground": "#f14c4c",
      "minimap.findMatchHighlight": "#15ac9170",
      "minimap.selectionHighlight": "#363636",
      "minimap.errorHighlight": "#f14c4c",
      "minimap.warningHighlight": "#ea7620",
      "minimap.background": "#181818",
      "sideBar.dropBackground": "#d6d6dd00",
      "editorGroup.emptyBackground": "#181818",
      "panelSection.border": "#383838",
      "statusBarItem.activeBackground": "#d6d6dd25",
      "settings.headerForeground": "#d6d6dd",
      "settings.focusedRowBackground": "#d6d6dd07",
      "walkThrough.embeddedEditorBackground": "#00000050",
      "breadcrumb.activeSelectionForeground": "#d6d6dd",
      "editorGutter.commentRangeForeground": "#d6d6dd",
      "debugExceptionWidget.background": "#1d1d1d",
      "debugExceptionWidget.border": "#383838",
      "commandCenter.background": "#292929",
      "commandCenter.foreground": "#c1c1c1",
      "commandCenter.activeBackground": "#1d1d1d",
      "titleBar.activeBackground": "#292929",
      "titleBar.activeForeground": "#d1d1d1",
      "titleBar.inactiveBackground": "#3c3b3c",
      "titleBar.inactiveForeground": "#cccccc99",
      "titleBar.border": "#383838",
    },
    encodedTokensColors: [],
    rules: [
      {
        token: "comment",
        foreground: "898989",
      },
      {
        token: "enumMember",
        foreground: "d6d6dd",
      },
      {
        token: "enumMember:cpp",
        foreground: "af9cff",
      },
      {
        token: "enumMember:c",
        foreground: "af9cff",
      },
      {
        token: "variable.constant",
        foreground: "83d6c5",
      },
      {
        token: "variable.defaultLibrary",
        foreground: "efb080",
      },
      {
        token: "variable.defaultLibrary.globalScope",
        foreground: "d1d1d1",
      },
      {
        token: "typeParameter:cpp",
        foreground: "add1de",
      },
      {
        token: "class.typeHint",
        foreground: "82d2ce",
      },
      {
        token: "variable.declaration.readonly:cpp",
        foreground: "d1d1d1",
      },
      {
        token: "variable.declaration.readonly:c",
        foreground: "d1d1d1",
      },
      {
        token: "variable.readonly:cpp",
        foreground: "d1d1d1",
      },
      {
        token: "variable.readonly:c",
        foreground: "d1d1d1",
      },
      {
        token: "method.declaration",
        foreground: "efefef",
        fontStyle: "bold",
      },
      {
        token: "function.builtin",
        foreground: "82d2ce",
      },
      {
        token: "class.builtin",
        foreground: "82d2ce",
      },
      {
        token: "class.declaration:python",
        foreground: "87c3ff",
      },
      {
        token: "class.decorator.builtin:python",
        foreground: "a8cc7c",
      },
      {
        token: "function.declaration",
        foreground: "efefef",
        fontStyle: "bold",
      },
      {
        token: "operatorOverload",
        foreground: "d1d1d1",
      },
      {
        token: "memberOperatorOverload",
        foreground: "d1d1d1",
      },
      {
        token: "namespace:cpp",
        foreground: "87c3ff",
      },
      {
        token: "variable.global:cpp",
        foreground: "a8cc7c",
      },
      {
        token: "variable.global:c",
        foreground: "a8cc7c",
      },
      {
        token: "type:cpp",
        foreground: "87c3ff",
      },
      {
        token: "function",
        foreground: "ebc88d",
      },
      {
        token: "function:cpp",
        foreground: "efefef",
        fontStyle: "bold",
      },
      {
        token: "class:python",
        foreground: "ebc88d",
      },
      {
        token: "*.decorator:python",
        foreground: "a8cc7c",
      },
      {
        token: "method:python",
        foreground: "ebc88d",
      },
      {
        token: "method:cpp",
        foreground: "efefef",
        fontStyle: "bold",
      },
      {
        token: "selfParameter",
        foreground: "cc7c8a",
      },
      {
        token: "macro",
        foreground: "a8cc7c",
      },
      {
        token: "property:cpp",
        foreground: "af9cff",
      },
      {
        token: "variable:javascript",
        foreground: "d1d1d1",
      },
      {
        token: "property.declaration:cpp",
        foreground: "af9cff",
      },
      {
        token: "property.declaration:c",
        foreground: "af9cff",
      },
      {
        token: "type:c",
        foreground: "87c3ff",
      },
      {
        token: "enum:cpp",
        foreground: "87c3ff",
      },
      {
        token: "enum:c",
        foreground: "87c3ff",
      },
      {
        token: "function:c",
        foreground: "efefef",
        fontStyle: "bold",
      },
      {
        token: "property:c",
        foreground: "af9cff",
      },
      {
        token: "function:cmake",
        foreground: "87c3ff",
      },
      {
        token: "builtinConstant.readonly.builtin:python",
        foreground: "82d2ce",
      },
      {
        token: "log.info",
        foreground: "ff00ff",
      },
      {
        token: "string.quoted.binary.single.python",
        foreground: "a8cc7c",
      },
      {
        token: "constant.language.false.cpp",
        foreground: "82d2ce",
      },
      {
        token: "constant.language.true.cpp",
        foreground: "82d2ce",
      },
      {
        token: "punctuation.definition.delayed.unison",
        foreground: "d6d6dd",
      },
      {
        token: "keyword.control.directive",
        foreground: "a8cc7c",
      },
      {
        token: "constant.other.ellipsis.python",
        foreground: "d1d1d1",
      },
      {
        token: "variable.other.generic-type.haskell",
        foreground: "83d6c5",
      },
      {
        token: "punctuation.definition.tag",
        foreground: "898989",
      },
      {
        token: "storage.type.haskell",
        foreground: "f8c762",
      },
      {
        token: "support.variable.magic.python",
        foreground: "d6d6dd",
      },
      {
        token: "punctuation.separator.parameters.python",
        foreground: "d6d6dd",
      },
      {
        token: "variable.parameter.function.language.special.self.python",
        foreground: "efb080",
      },
      {
        token: "variable.language.this.cpp",
        foreground: "82d2ce",
      },
      {
        token: "storage.modifier.lifetime.rust",
        foreground: "d6d6dd",
      },
      {
        token: "support.function.std.rust",
        foreground: "aaa0fa",
      },
      {
        token: "entity.name.lifetime.rust",
        foreground: "efb080",
      },
      {
        token: "variable.language.rust",
        foreground: "d6d6dd",
      },
      {
        token: "support.constant.edge",
        foreground: "83d6c5",
      },
      {
        token: "constant.other.character-class.regexp",
        foreground: "d6d6dd",
      },
      {
        token: "keyword.operator.quantifier.regexp",
        foreground: "f8c762",
      },
      {
        token: "punctuation.definition.string.begin",
        foreground: "e394dc",
      },
      {
        token: "punctuation.definition.string.end",
        foreground: "e394dc",
      },
      {
        token: "variable.parameter.function",
        foreground: "d6d6dd",
      },
      {
        token: "comment markup.link",
        foreground: "6d6d6d",
      },
      {
        token: "markup.changed.diff",
        foreground: "efb080",
      },
      {
        token: "meta.diff.header.from-file",
        foreground: "aaa0fa",
      },
      {
        token: "meta.diff.header.to-file",
        foreground: "aaa0fa",
      },
      {
        token: "markup.inserted.diff",
        foreground: "e394dc",
      },
      {
        token: "markup.deleted.diff",
        foreground: "d6d6dd",
      },
      {
        token: "meta.function.c",
        foreground: "d6d6dd",
      },
      {
        token: "punctuation.section.block.begin.bracket.curly.cpp",
        foreground: "d6d6dd",
      },
      {
        token: "punctuation.section.block.end.bracket.curly.cpp",
        foreground: "d6d6dd",
      },
      {
        token: "punctuation.terminator.statement.c",
        foreground: "d6d6dd",
      },
      {
        token: "punctuation.section.block.begin.bracket.curly.c",
        foreground: "d6d6dd",
      },
      {
        token: "punctuation.section.block.end.bracket.curly.c",
        foreground: "d6d6dd",
      },
      {
        token: "punctuation.terminator.statement.cpp",
        foreground: "d6d6dd",
      },
      {
        token: "support.class.java",
        foreground: "aaa0fa",
      },
      {
        token: "punctuation.separator.key-value.json",
        foreground: "d6d6dd",
      },
      {
        token: "meta.tag.template",
        foreground: "e394dc",
      },
      {
        token: "variable.language.self",
        foreground: "d6d6dd",
      },
      {
        token: "constant.other.symbol",
        foreground: "d6d6dd",
      },
      {
        token: "string",
        foreground: "ffffff", // Set the color for strings (including import paths)
      },
      {
        token: "support.module.path",
        foreground: "ffffff", // If there is a specific token for paths
      },
    ],
  } satisfies editor.IStandaloneThemeData;
}
