declare module "@carbon/react";
declare module "@carbon/themes";
declare module "@carbon/icons-react";
declare module "react-router-dom";
declare module "styled-components";
declare module "@carbon/pictograms-react";
declare module "react-flow-renderer";
declare module "react-syntax-highlighter";
declare module "react-syntax-highlighter/dist/esm/styles/prism";
declare module "react-syntax-highlighter/dist/esm/styles/hljs";
declare module "react-contenteditable";
declare module "uuid";
declare module "moment";
declare let module: any;
