// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "stephen.sanwo@icloud.com",
        "contact": {
            "name": "Stephen Sanwo",
            "email": "stephen.sanwo@icloud.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/folder": {
            "get": {
                "description": "Query Folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Query Folder",
                "operationId": "get-folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Folder",
                        "schema": {
                            "$ref": "#/definitions/types.Folder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create New Folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Create New Folder",
                "operationId": "post-folder",
                "parameters": [
                    {
                        "description": "Folder Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.MutateFolder"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Folder Id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.FieldErrors"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Delete Folder",
                "operationId": "delete-folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Records Deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Patch Folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Patch Folder",
                "operationId": "patch-folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Folder Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.MutateFolder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Response",
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.UpdateDataResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.FieldErrors"
                        }
                    }
                }
            }
        },
        "/folder-list": {
            "get": {
                "description": "Query folder list from db or cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Query folder list from db or cache",
                "operationId": "get-folder-list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.FolderList"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/folders": {
            "get": {
                "description": "Query all folders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Query all folders",
                "operationId": "get-folders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Folder"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get-public-note": {
            "get": {
                "description": "Query Public Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public Note"
                ],
                "summary": "Query Public Note",
                "operationId": "get-public-note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Public Note ID",
                        "name": "public_note_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Public Note",
                        "schema": {
                            "$ref": "#/definitions/types.Note"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get-shared-note": {
            "get": {
                "description": "Query Shared Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Query Shared Note",
                "operationId": "get-shared-note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Note ID",
                        "name": "note_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Public Note ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/note": {
            "get": {
                "description": "Query Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Query Note",
                "operationId": "get-note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Note ID",
                        "name": "note_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Note",
                        "schema": {
                            "$ref": "#/definitions/types.Note"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create New Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Create New Note",
                "operationId": "post-note",
                "parameters": [
                    {
                        "description": "Note Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.MutateNote"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Note Id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.FieldErrors"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Delete Note",
                "operationId": "delete-note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Note ID",
                        "name": "note_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Records Deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Patch Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Patch Note",
                "operationId": "patch-note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Note ID",
                        "name": "note_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Note Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.PatchNote"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Response",
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.UpdateDataResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.FieldErrors"
                        }
                    }
                }
            }
        },
        "/note-summary": {
            "get": {
                "description": "Query Note Summary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Query Note Summary",
                "operationId": "get-note-summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Note ID",
                        "name": "note_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "NoteSummary",
                        "schema": {
                            "$ref": "#/definitions/types.NoteSummary"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notes": {
            "get": {
                "description": "Query all notes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Query all notes",
                "operationId": "get-notes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notes",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Note"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping the server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ping"
                ],
                "summary": "Ping the server",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.BaseResponse"
                        }
                    }
                }
            }
        },
        "/publish-public-note": {
            "post": {
                "description": "Create New Public Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Create New Public Note",
                "operationId": "publish-public-note",
                "parameters": [
                    {
                        "description": "Public Note Request Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.PostPublicNote"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Public Note Id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/axon-server_lib_types.FieldErrors"
                        }
                    }
                }
            }
        },
        "/upload-media": {
            "post": {
                "description": "Upload a media file",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Upload media file",
                "operationId": "upload-media",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Media file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "File uploaded successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "axon-server_lib_types.BaseResponse": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "axon-server_lib_types.FieldErrors": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "axon-server_lib_types.MutateFolder": {
            "type": "object",
            "required": [
                "folder_name"
            ],
            "properties": {
                "folder_name": {
                    "type": "string"
                }
            }
        },
        "axon-server_lib_types.MutateNote": {
            "type": "object",
            "required": [
                "description",
                "folder_id",
                "note_name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "note_name": {
                    "type": "string"
                }
            }
        },
        "axon-server_lib_types.PatchNote": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "note_name": {
                    "type": "string"
                }
            }
        },
        "axon-server_lib_types.PostPublicNote": {
            "type": "object",
            "required": [
                "folder_id",
                "note_id",
                "public_note_id"
            ],
            "properties": {
                "folder_id": {
                    "type": "string"
                },
                "note_id": {
                    "type": "string"
                },
                "public_note_id": {
                    "type": "string"
                }
            }
        },
        "axon-server_lib_types.UpdateDataResponse": {
            "type": "object",
            "properties": {
                "MatchedCount": {
                    "type": "integer"
                },
                "ModifiedCount": {
                    "type": "integer"
                },
                "UpsertedCount": {
                    "type": "integer"
                },
                "UpsertedID": {
                    "type": "string"
                }
            }
        },
        "types.Edge": {
            "type": "object",
            "properties": {
                "animated": {
                    "type": "boolean"
                },
                "edge_id": {
                    "type": "string"
                },
                "edge_type": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "note_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "types.Folder": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "folder_name": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "types.FolderList": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "folder_name": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.NoteSummary"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "types.Node": {
            "type": "object",
            "properties": {
                "arialLabel": {
                    "type": "string"
                },
                "className": {
                    "type": "string"
                },
                "connectable": {
                    "type": "boolean"
                },
                "content": {
                    "$ref": "#/definitions/types.NodeContent"
                },
                "data": {
                    "$ref": "#/definitions/types.NodeData"
                },
                "deletable": {
                    "type": "boolean"
                },
                "dragHandle": {
                    "type": "string"
                },
                "dragging": {
                    "type": "boolean"
                },
                "expandParent": {
                    "type": "boolean"
                },
                "extent": {
                    "type": "string"
                },
                "focusable": {
                    "type": "boolean"
                },
                "folder_id": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "hidden": {
                    "type": "boolean"
                },
                "id": {
                    "description": "Same as node id",
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "note_id": {
                    "type": "string"
                },
                "parentNode": {
                    "type": "string"
                },
                "position": {
                    "$ref": "#/definitions/types.NodePosition"
                },
                "positionAbsolute": {
                    "type": "boolean"
                },
                "selectable": {
                    "type": "boolean"
                },
                "selected": {
                    "type": "boolean"
                },
                "sourcePosition": {
                    "$ref": "#/definitions/types.NodePosition"
                },
                "style": {
                    "type": "object",
                    "additionalProperties": true
                },
                "targetPosition": {
                    "$ref": "#/definitions/types.NodePosition"
                },
                "type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "width": {
                    "type": "number"
                },
                "zIndex": {
                    "type": "integer"
                }
            }
        },
        "types.NodeCodeContent": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "fileName": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "validLanguage": {
                    "type": "boolean"
                }
            }
        },
        "types.NodeContent": {
            "type": "object",
            "properties": {
                "content_data": {
                    "type": "string"
                },
                "content_header": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                }
            }
        },
        "types.NodeData": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/types.NodeCodeContent"
                },
                "contentType": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "link": {
                    "$ref": "#/definitions/types.NodeLinkContent"
                },
                "markdown": {
                    "$ref": "#/definitions/types.NodeMarkdownContent"
                },
                "media": {
                    "$ref": "#/definitions/types.NodeMediaContent"
                },
                "node_id": {
                    "type": "string"
                },
                "node_styles": {
                    "$ref": "#/definitions/types.NodeStyles"
                },
                "node_theme": {
                    "$ref": "#/definitions/types.NodeThemes"
                },
                "table": {
                    "$ref": "#/definitions/types.NodeTableContent"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "types.NodeLinkContent": {
            "type": "object",
            "properties": {
                "isLoadable": {
                    "type": "boolean"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "types.NodeMarkdownContent": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "showPreview": {
                    "type": "boolean"
                }
            }
        },
        "types.NodeMediaContent": {
            "type": "object",
            "properties": {
                "fileName": {
                    "type": "string"
                },
                "remoteUrl": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.NodePosition": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "types.NodeStyles": {
            "type": "object",
            "properties": {
                "background_color": {
                    "type": "string"
                },
                "border_color": {
                    "type": "string"
                },
                "font_alignment": {
                    "type": "string"
                },
                "font_color": {
                    "type": "string"
                },
                "font_weight": {
                    "type": "integer"
                }
            }
        },
        "types.NodeTableContent": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "renderTable": {
                    "type": "boolean"
                }
            }
        },
        "types.NodeThemes": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                }
            }
        },
        "types.Note": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Edge"
                    }
                },
                "folder_id": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Node"
                    }
                },
                "note_id": {
                    "type": "string"
                },
                "note_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "types.NoteSummary": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "note_id": {
                    "type": "string"
                },
                "note_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8100",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Axon Core API",
	Description:      "Axon Core API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
