// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "stephen.sanwo@icloud.com",
        "contact": {
            "name": "Stephen Sanwo",
            "email": "stephen.sanwo@icloud.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/callback": {
            "get": {
                "description": "AuthCallback",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "AuthCallback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.BaseResponse"
                        }
                    }
                }
            }
        },
        "/folder": {
            "get": {
                "description": "Query Folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Query Folder",
                "operationId": "get-folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Folder",
                        "schema": {
                            "$ref": "#/definitions/types.Folder"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create New Folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Create New Folder",
                "operationId": "post-folder",
                "parameters": [
                    {
                        "description": "Folder Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.MutateFolder"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Folder Id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/types.FieldErrors"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Delete Folder",
                "operationId": "delete-folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Records Deleted",
                        "schema": {
                            "type": "int"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Patch Folder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Patch Folder",
                "operationId": "patch-folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Folder Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.MutateFolder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Folder Update Result",
                        "schema": {
                            "$ref": "#/definitions/types.UpdateDataResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/types.FieldErrors"
                        }
                    }
                }
            }
        },
        "/folders": {
            "get": {
                "description": "FoldersHandler",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "FoldersHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Folder"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/note": {
            "get": {
                "description": "Query Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Query Note",
                "operationId": "get-note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Note ID",
                        "name": "note_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Note",
                        "schema": {
                            "$ref": "#/definitions/types.Note"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create New Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Create New Note",
                "operationId": "post-note",
                "parameters": [
                    {
                        "description": "Note Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.MutateNote"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Note Id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/types.FieldErrors"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Delete Note",
                "operationId": "delete-note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Note ID",
                        "name": "note_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Records Deleted",
                        "schema": {
                            "type": "int"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "description": "Patch Note",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Patch Note",
                "operationId": "patch-note",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Note ID",
                        "name": "note_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Note Object",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.PatchNote"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Note Update Result",
                        "schema": {
                            "$ref": "#/definitions/types.UpdateDataResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Unprocessible Entity",
                        "schema": {
                            "$ref": "#/definitions/types.FieldErrors"
                        }
                    }
                }
            }
        },
        "/notes": {
            "get": {
                "description": "Query all notes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Note"
                ],
                "summary": "Query all notes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "folder_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.Note"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping the server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ping"
                ],
                "summary": "Ping the server",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/types.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.BaseResponse": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "types.FieldErrors": {
            "type": "object",
            "properties": {
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "msg": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "types.Folder": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "types.MutateFolder": {
            "type": "object",
            "required": [
                "folder_name"
            ],
            "properties": {
                "folder_name": {
                    "type": "string"
                }
            }
        },
        "types.MutateNote": {
            "type": "object",
            "required": [
                "folder_id",
                "note_description",
                "note_name"
            ],
            "properties": {
                "folder_id": {
                    "type": "string"
                },
                "note_description": {
                    "type": "string"
                },
                "note_name": {
                    "type": "string"
                }
            }
        },
        "types.Note": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "note_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "types.PatchNote": {
            "type": "object",
            "required": [
                "note_description",
                "note_name"
            ],
            "properties": {
                "note_description": {
                    "type": "string"
                },
                "note_name": {
                    "type": "string"
                }
            }
        },
        "types.UpdateDataResponse": {
            "type": "object",
            "properties": {
                "MatchedCount": {
                    "type": "integer"
                },
                "ModifiedCount": {
                    "type": "integer"
                },
                "UpsertedCount": {
                    "type": "integer"
                },
                "UpsertedID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8100",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Axon Core API",
	Description:      "Axon Core API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
