// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "stephen.sanwo@icloud.com",
        "contact": {
            "name": "Stephen Sanwo",
            "email": "stephen.sanwo@icloud.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/axon-events": {
            "get": {
                "description": "Query folder list from db or cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Folder"
                ],
                "summary": "Query folder list from db or cache",
                "operationId": "axon-events",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.FolderList"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping the server",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ping"
                ],
                "summary": "Ping the server",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/axon-events_lib_types.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "axon-events_lib_types.BaseResponse": {
            "type": "object",
            "properties": {
                "message": {}
            }
        },
        "types.FolderList": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "folder_name": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "notes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Note"
                    }
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "types.Note": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "last_edited": {
                    "type": "string"
                },
                "note_id": {
                    "type": "string"
                },
                "note_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8201",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Axon Events API",
	Description:      "Axon Events API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
