basePath: /
definitions:
  axon-events_lib_types.BaseResponse:
    properties:
      message: {}
    type: object
  types.FolderList:
    properties:
      date_created:
        type: string
      folder_id:
        type: string
      folder_name:
        type: string
      last_edited:
        type: string
      notes:
        items:
          $ref: '#/definitions/types.Note'
        type: array
      user_id:
        type: string
    type: object
  types.Note:
    properties:
      date_created:
        type: string
      description:
        type: string
      folder_id:
        type: string
      last_edited:
        type: string
      note_id:
        type: string
      note_name:
        type: string
      user_id:
        type: string
    type: object
host: 127.0.0.1:8201
info:
  contact:
    email: stephen.sanwo@icloud.com
    name: Stephen Sanwo
  description: Axon Events API
  license:
    name: MIT
    url: https://mit-license.org
  termsOfService: stephen.sanwo@icloud.com
  title: Axon Events API
  version: "1.0"
paths:
  /axon-events:
    get:
      consumes:
      - application/json
      description: Query folder list from db or cache
      operationId: axon-events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.FolderList'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Query folder list from db or cache
      tags:
      - Folder
  /ping:
    get:
      description: Ping the server
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/axon-events_lib_types.BaseResponse'
      summary: Ping the server
      tags:
      - Ping
swagger: "2.0"
